package com.gsr.janasanthwanam.dataaccess.entity;
// Generated Jul 25, 2017 11:57:37 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblApplicationUserApprovalLevel generated by hbm2java
 */
@Entity
@Table(name = "tbl_application_user_approval_level")
public class TblApplicationUserApprovalLevel implements java.io.Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = -8770658069650141875L;
  private Integer pkApplicationUserApprovalLevel;
  private TblApplication tblApplication;
  private int fkUserApprovalLevel;

  public TblApplicationUserApprovalLevel() {
  }

  public TblApplicationUserApprovalLevel(TblApplication tblApplication, int fkUserApprovalLevel) {
    this.tblApplication = tblApplication;
    this.fkUserApprovalLevel = fkUserApprovalLevel;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)

  @Column(name = "pk_application_user_approval_level", unique = true, nullable = false)
  public Integer getPkApplicationUserApprovalLevel() {
    return this.pkApplicationUserApprovalLevel;
  }

  public void setPkApplicationUserApprovalLevel(Integer pkApplicationUserApprovalLevel) {
    this.pkApplicationUserApprovalLevel = pkApplicationUserApprovalLevel;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fk_application", nullable = false)
  public TblApplication getTblApplication() {
    return this.tblApplication;
  }

  public void setTblApplication(TblApplication tblApplication) {
    this.tblApplication = tblApplication;
  }

  @Column(name = "fk_user_approval_level", nullable = false)
  public int getFkUserApprovalLevel() {
    return this.fkUserApprovalLevel;
  }

  public void setFkUserApprovalLevel(int fkUserApprovalLevel) {
    this.fkUserApprovalLevel = fkUserApprovalLevel;
  }

}
