package com.gsr.janasanthwanam.dataaccess.entity;
// Generated Jul 25, 2017 11:57:37 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUserApprovalLevel generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_approval_level")
public class TblUserApprovalLevel implements java.io.Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = 7892382834888489300L;
  private Integer pkUserApprovalLevel;
  private TblApprovalLevel tblApprovalLevel;
  private TblUser tblUser;

  public TblUserApprovalLevel() {
  }

  public TblUserApprovalLevel(TblApprovalLevel tblApprovalLevel, TblUser tblUser) {
    this.tblApprovalLevel = tblApprovalLevel;
    this.tblUser = tblUser;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)

  @Column(name = "pk_user_approval_level", unique = true, nullable = false)
  public Integer getPkUserApprovalLevel() {
    return this.pkUserApprovalLevel;
  }

  public void setPkUserApprovalLevel(Integer pkUserApprovalLevel) {
    this.pkUserApprovalLevel = pkUserApprovalLevel;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fk_approval_level", nullable = false)
  public TblApprovalLevel getTblApprovalLevel() {
    return this.tblApprovalLevel;
  }

  public void setTblApprovalLevel(TblApprovalLevel tblApprovalLevel) {
    this.tblApprovalLevel = tblApprovalLevel;
  }

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "fk_user", nullable = false)
  public TblUser getTblUser() {
    return this.tblUser;
  }

  public void setTblUser(TblUser tblUser) {
    this.tblUser = tblUser;
  }

}
