package com.gsr.janasanthwanam.dataaccess.entity;
// Generated Jul 25, 2017 11:57:37 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TblUser generated by hbm2java
 */
@Entity
@Table(name = "tbl_user")
public class TblUser implements java.io.Serializable {

  /**
   * 
   */
  private static final long serialVersionUID = 3962747676776707456L;
  private Integer pkUser;
  private String username;
  private String password;
  private Set<TblUserApprovalLevel> tblUserApprovalLevels = new HashSet<TblUserApprovalLevel>(0);
//  private Set<TblApplication> tblApplicationsForFkLastUpdatedUser = new HashSet<TblApplication>(0);
//  private Set<TblApplication> tblApplicationsForFkCreatedUser = new HashSet<TblApplication>(0);

  public TblUser() {
  }

  public TblUser(String username, String password) {
    this.username = username;
    this.password = password;
  }

  

  @Id
  @GeneratedValue(strategy = IDENTITY)

  @Column(name = "pk_user", unique = true, nullable = false)
  public Integer getPkUser() {
    return this.pkUser;
  }

  public void setPkUser(Integer pkUser) {
    this.pkUser = pkUser;
  }

  @Column(name = "username", nullable = false, length = 10)
  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  @Column(name = "password", nullable = false, length = 10)
  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  @OneToMany(fetch = FetchType.EAGER, mappedBy = "tblUser")
  public Set<TblUserApprovalLevel> getTblUserApprovalLevels() {
    return this.tblUserApprovalLevels;
  }

  public void setTblUserApprovalLevels(Set<TblUserApprovalLevel> tblUserApprovalLevels) {
    this.tblUserApprovalLevels = tblUserApprovalLevels;
  }

//  @OneToMany(fetch = FetchType.EAGER, mappedBy = "tblUserByFkLastUpdatedUser")
//  public Set<TblApplication> getTblApplicationsForFkLastUpdatedUser() {
//    return this.tblApplicationsForFkLastUpdatedUser;
//  }
//
//  public void setTblApplicationsForFkLastUpdatedUser(
//      Set<TblApplication> tblApplicationsForFkLastUpdatedUser) {
//    this.tblApplicationsForFkLastUpdatedUser = tblApplicationsForFkLastUpdatedUser;
//  }
//
//  @OneToMany(fetch = FetchType.EAGER, mappedBy = "tblUserByFkCreatedUser")
//  public Set<TblApplication> getTblApplicationsForFkCreatedUser() {
//    return this.tblApplicationsForFkCreatedUser;
//  }
//
//  public void setTblApplicationsForFkCreatedUser(
//      Set<TblApplication> tblApplicationsForFkCreatedUser) {
//    this.tblApplicationsForFkCreatedUser = tblApplicationsForFkCreatedUser;
//  }

}
